title: Qiqi Liu # your name (or website title) here
logo: "/images/QiqiLiu.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A MS Marketing Analytics student at Simon Business School with an interest in Marketing Analytics, Digital Marketing and Business Intelligence. 
  <br><br>
  Specialties: SQL, Tableau, R, Python, Advanced Excel, Google Analytics, A/B Testing, Linear Regression, Logistic Regression, Cluster Analysis
  <br><br>
  <a href="https://www.linkedin.com/in/qiqi-liu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-167495936-1 # your Google Analytics tracking ID here
