title: Qiqi Liu # your name (or website title) here
logo: "/images/QiqiLiu.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS in Marketing Analytics 
  <br><br>
  Business Analytics|Data Analytics|Marketing Analytics|Digital Marketing 
  <br><br>
  <a href="https://www.linkedin.com/in/qiqi-liu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-54516992-1 # your Google Analytics tracking ID here
